// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core_json.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_core_5fjson_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_core_5fjson_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "json.pb.h"
#include "field_mask.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_core_5fjson_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_core_5fjson_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_core_5fjson_2eproto;
class core_json_pair;
struct core_json_pairDefaultTypeInternal;
extern core_json_pairDefaultTypeInternal _core_json_pair_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::core_json_pair* Arena::CreateMaybeMessage<::core_json_pair>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class core_json_pair final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:core_json_pair) */ {
 public:
  inline core_json_pair() : core_json_pair(nullptr) {}
  ~core_json_pair() override;
  explicit constexpr core_json_pair(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  core_json_pair(const core_json_pair& from);
  core_json_pair(core_json_pair&& from) noexcept
    : core_json_pair() {
    *this = ::std::move(from);
  }

  inline core_json_pair& operator=(const core_json_pair& from) {
    CopyFrom(from);
    return *this;
  }
  inline core_json_pair& operator=(core_json_pair&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const core_json_pair& default_instance() {
    return *internal_default_instance();
  }
  static inline const core_json_pair* internal_default_instance() {
    return reinterpret_cast<const core_json_pair*>(
               &_core_json_pair_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(core_json_pair& a, core_json_pair& b) {
    a.Swap(&b);
  }
  inline void Swap(core_json_pair* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(core_json_pair* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  core_json_pair* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<core_json_pair>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const core_json_pair& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const core_json_pair& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(core_json_pair* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "core_json_pair";
  }
  protected:
  explicit core_json_pair(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBufferFieldNumber = 1,
    kQueryKeyFieldNumber = 2,
  };
  // .JSON_value buffer = 1;
  bool has_buffer() const;
  private:
  bool _internal_has_buffer() const;
  public:
  void clear_buffer();
  const ::JSON_value& buffer() const;
  PROTOBUF_NODISCARD ::JSON_value* release_buffer();
  ::JSON_value* mutable_buffer();
  void set_allocated_buffer(::JSON_value* buffer);
  private:
  const ::JSON_value& _internal_buffer() const;
  ::JSON_value* _internal_mutable_buffer();
  public:
  void unsafe_arena_set_allocated_buffer(
      ::JSON_value* buffer);
  ::JSON_value* unsafe_arena_release_buffer();

  // .FieldMask queryKey = 2;
  bool has_querykey() const;
  private:
  bool _internal_has_querykey() const;
  public:
  void clear_querykey();
  const ::FieldMask& querykey() const;
  PROTOBUF_NODISCARD ::FieldMask* release_querykey();
  ::FieldMask* mutable_querykey();
  void set_allocated_querykey(::FieldMask* querykey);
  private:
  const ::FieldMask& _internal_querykey() const;
  ::FieldMask* _internal_mutable_querykey();
  public:
  void unsafe_arena_set_allocated_querykey(
      ::FieldMask* querykey);
  ::FieldMask* unsafe_arena_release_querykey();

  // @@protoc_insertion_point(class_scope:core_json_pair)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::JSON_value* buffer_;
  ::FieldMask* querykey_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_core_5fjson_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// core_json_pair

// .JSON_value buffer = 1;
inline bool core_json_pair::_internal_has_buffer() const {
  return this != internal_default_instance() && buffer_ != nullptr;
}
inline bool core_json_pair::has_buffer() const {
  return _internal_has_buffer();
}
inline const ::JSON_value& core_json_pair::_internal_buffer() const {
  const ::JSON_value* p = buffer_;
  return p != nullptr ? *p : reinterpret_cast<const ::JSON_value&>(
      ::_JSON_value_default_instance_);
}
inline const ::JSON_value& core_json_pair::buffer() const {
  // @@protoc_insertion_point(field_get:core_json_pair.buffer)
  return _internal_buffer();
}
inline void core_json_pair::unsafe_arena_set_allocated_buffer(
    ::JSON_value* buffer) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(buffer_);
  }
  buffer_ = buffer;
  if (buffer) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:core_json_pair.buffer)
}
inline ::JSON_value* core_json_pair::release_buffer() {
  
  ::JSON_value* temp = buffer_;
  buffer_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::JSON_value* core_json_pair::unsafe_arena_release_buffer() {
  // @@protoc_insertion_point(field_release:core_json_pair.buffer)
  
  ::JSON_value* temp = buffer_;
  buffer_ = nullptr;
  return temp;
}
inline ::JSON_value* core_json_pair::_internal_mutable_buffer() {
  
  if (buffer_ == nullptr) {
    auto* p = CreateMaybeMessage<::JSON_value>(GetArenaForAllocation());
    buffer_ = p;
  }
  return buffer_;
}
inline ::JSON_value* core_json_pair::mutable_buffer() {
  ::JSON_value* _msg = _internal_mutable_buffer();
  // @@protoc_insertion_point(field_mutable:core_json_pair.buffer)
  return _msg;
}
inline void core_json_pair::set_allocated_buffer(::JSON_value* buffer) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(buffer_);
  }
  if (buffer) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(buffer));
    if (message_arena != submessage_arena) {
      buffer = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, buffer, submessage_arena);
    }
    
  } else {
    
  }
  buffer_ = buffer;
  // @@protoc_insertion_point(field_set_allocated:core_json_pair.buffer)
}

// .FieldMask queryKey = 2;
inline bool core_json_pair::_internal_has_querykey() const {
  return this != internal_default_instance() && querykey_ != nullptr;
}
inline bool core_json_pair::has_querykey() const {
  return _internal_has_querykey();
}
inline const ::FieldMask& core_json_pair::_internal_querykey() const {
  const ::FieldMask* p = querykey_;
  return p != nullptr ? *p : reinterpret_cast<const ::FieldMask&>(
      ::_FieldMask_default_instance_);
}
inline const ::FieldMask& core_json_pair::querykey() const {
  // @@protoc_insertion_point(field_get:core_json_pair.queryKey)
  return _internal_querykey();
}
inline void core_json_pair::unsafe_arena_set_allocated_querykey(
    ::FieldMask* querykey) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(querykey_);
  }
  querykey_ = querykey;
  if (querykey) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:core_json_pair.queryKey)
}
inline ::FieldMask* core_json_pair::release_querykey() {
  
  ::FieldMask* temp = querykey_;
  querykey_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::FieldMask* core_json_pair::unsafe_arena_release_querykey() {
  // @@protoc_insertion_point(field_release:core_json_pair.queryKey)
  
  ::FieldMask* temp = querykey_;
  querykey_ = nullptr;
  return temp;
}
inline ::FieldMask* core_json_pair::_internal_mutable_querykey() {
  
  if (querykey_ == nullptr) {
    auto* p = CreateMaybeMessage<::FieldMask>(GetArenaForAllocation());
    querykey_ = p;
  }
  return querykey_;
}
inline ::FieldMask* core_json_pair::mutable_querykey() {
  ::FieldMask* _msg = _internal_mutable_querykey();
  // @@protoc_insertion_point(field_mutable:core_json_pair.queryKey)
  return _msg;
}
inline void core_json_pair::set_allocated_querykey(::FieldMask* querykey) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(querykey_);
  }
  if (querykey) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(querykey));
    if (message_arena != submessage_arena) {
      querykey = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, querykey, submessage_arena);
    }
    
  } else {
    
  }
  querykey_ = querykey;
  // @@protoc_insertion_point(field_set_allocated:core_json_pair.queryKey)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_core_5fjson_2eproto
